// 試用サンプル PDF を生成する（public/sample/sample.pdf）。
// 3 ページ構成: 1-2 ページは通常の縦置き、3 ページ目は /Rotate 90 の横置き（座標変換の確認用）。
// 実行: npm run sample
import { PDFDocument, StandardFonts, rgb, degrees } from '@cantoo/pdf-lib';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../public/sample/sample.pdf');

const PAGE = { width: 595.28, height: 841.89 }; // A4
const MARGIN = 64;
const BODY_SIZE = 11;
const LINE = 16;

const PARAGRAPHS_P1 = [
  ['title', 'Toward AI-Assisted Ship Design Review: A Sample Manuscript'],
  ['meta', 'K. Wakita, OCEANS, The University of Osaka  |  Draft for internal review  |  2026'],
  ['h', 'Abstract'],
  ['p', 'This document is a sample manuscript for trying out the PDF review tool. Select any sentence with the mouse and add a comment. Comments are stored inside the PDF as standard annotations, so they remain visible in Acrobat, macOS Preview and Zotero after you save the file.'],
  ['h', '1. Introduction'],
  ['p', 'Ship design is an iterative process in which requirements, hull form, general arrangement and machinery are negotiated over many rounds of review. Each round produces documents that must be read carefully by several people. In a research group this is also how students learn: a draft goes to a supervisor, comes back with comments, and is revised.'],
  ['p', 'Existing tools either require a commercial license, store documents on a third-party server, or make it hard to merge comments from several reviewers. The tool you are using now keeps the PDF entirely inside the browser. Nothing is uploaded.'],
  ['p', 'The remainder of this sample is filler text so that there is enough to select. Try highlighting a phrase, adding a sticky note in the margin, replying to your own comment, and then saving the PDF with Cmd+S.'],
];

const PARAGRAPHS_P2 = [
  ['h', '2. Method'],
  ['p', 'We consider a review workflow with three roles: an author, one or more reviewers, and a person who consolidates the feedback. Each reviewer receives the same PDF, annotates it independently, and returns the annotated copy through the usual channels (Slack, Box or e-mail).'],
  ['p', 'The consolidator opens one copy in the tool and imports the other copies. Comments with the same identity are merged, and the remaining comments are shown side by side with the reviewer name and a colour per reviewer. The result can be saved as a single PDF or exported as a Markdown list grouped by page.'],
  ['h', '3. Results'],
  ['p', 'Table 1 summarises the annotation types that survive a round trip through the tool. Highlight and sticky-note comments, including replies, keep their author, timestamp and text. Other annotation types present in the file are left untouched.'],
  ['table', 'Type            Written   Read back   Notes'],
  ['table', 'Highlight       yes       yes         QuadPoints + Popup'],
  ['table', 'Text (note)     yes       yes         Icon: Comment'],
  ['table', 'Reply           yes       yes         IRT / RT R'],
  ['table', 'Ink, FreeText   no        counted     preserved as-is'],
  ['h', '4. Discussion'],
  ['p', 'Because the geometry of every comment is stored in PDF user space, comments keep their position when the page is rotated or when the viewer zooms. The next page is rotated by 90 degrees to demonstrate this.'],
];

const PARAGRAPHS_P3 = [
  ['h', '5. A rotated page'],
  ['p', 'This page carries a /Rotate 90 entry. The text below is drawn so that it reads upright in a viewer. Highlight a few words here to confirm that the highlight lands on the right place after saving and reopening.'],
  ['p', 'Acknowledgements. This sample was generated by scripts/make-sample.mjs using @cantoo/pdf-lib.'],
];

function wrap(text, font, size, maxWidth) {
  const words = text.split(' ');
  const lines = [];
  let line = '';
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) > maxWidth && line) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

async function main() {
  const doc = await PDFDocument.create();
  doc.setTitle('Sample manuscript for lab-pdf-editor');
  doc.setAuthor('OCEANS-UOsaka');
  const serif = await doc.embedFont(StandardFonts.TimesRoman);
  const serifBold = await doc.embedFont(StandardFonts.TimesRomanBold);
  const mono = await doc.embedFont(StandardFonts.Courier);

  const styles = {
    title: { font: serifBold, size: 18, gap: 10 },
    meta: { font: serif, size: 10, gap: 18 },
    h: { font: serifBold, size: 13, gap: 6, before: 8 },
    p: { font: serif, size: BODY_SIZE, gap: 8 },
    table: { font: mono, size: 9.5, gap: 0 },
  };

  // 縦置きページ: 上から下へ行を積む
  function drawUpright(page, blocks) {
    const maxWidth = PAGE.width - MARGIN * 2;
    let y = PAGE.height - MARGIN;
    for (const [kind, text] of blocks) {
      const st = styles[kind];
      y -= st.before ?? 0;
      for (const line of wrap(text, st.font, st.size, maxWidth)) {
        y -= st.size * 1.35;
        page.drawText(line, { x: MARGIN, y, size: st.size, font: st.font, color: rgb(0.1, 0.1, 0.1) });
      }
      y -= st.gap;
    }
  }

  // /Rotate 90 のページ: 閲覧者に正立して見えるよう、ユーザ空間では 90° 回して描く
  function drawRotated(page, blocks) {
    const maxWidth = PAGE.height - MARGIN * 2; // 閲覧者にとっての横幅
    let x = MARGIN;
    for (const [kind, text] of blocks) {
      const st = styles[kind];
      x += st.before ?? 0;
      for (const line of wrap(text, st.font, st.size, maxWidth)) {
        x += st.size * 1.35;
        page.drawText(line, { x, y: MARGIN, size: st.size, font: st.font, rotate: degrees(90), color: rgb(0.1, 0.1, 0.1) });
      }
      x += st.gap;
    }
  }

  const p1 = doc.addPage([PAGE.width, PAGE.height]);
  drawUpright(p1, PARAGRAPHS_P1);
  const p2 = doc.addPage([PAGE.width, PAGE.height]);
  drawUpright(p2, PARAGRAPHS_P2);
  const p3 = doc.addPage([PAGE.width, PAGE.height]);
  p3.setRotation(degrees(90));
  drawRotated(p3, PARAGRAPHS_P3);

  for (const [i, page] of doc.getPages().entries()) {
    page.drawText(`${i + 1} / 3`, { x: PAGE.width / 2 - 10, y: 30, size: 9, font: serif, color: rgb(0.4, 0.4, 0.4) });
  }

  const bytes = await doc.save();
  await mkdir(dirname(out), { recursive: true });
  await writeFile(out, bytes);
  console.log(`wrote ${out} (${bytes.byteLength} bytes)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
